### PR TITLE
Added xMax and widthMin to bounds.

### PR DESCRIPTION
**Pull request by peboCodemill**
Enables me to set inner boundaries of a resizable. Needed for comparing
values between several resizables. Please return to me with any questions but this feature would make my life easier!

### CODE REVIEW

**Comment by mgechev** [comment]
@peboCodemill would you explain the use case in more details?

**Comment by peboCodemill** [comment]
image

I hope this image explains my use case. It could probably be a good addition to y / height as well but I'm fine with just adding this for X.

**Comment by peboCodemill** [comment]
I ended up with writing the resizable logic myself since the ngOnChanges in the resizable component hindered me from updating (e.g. resetting) the values. I have a use case where I zoom the resizable boxes but that functionality was blocked by the inner recalculations. Is the ngOnChanges really needed or could it be made optional somehow?

**Comment by mgechev** [comment]
Thanks for the comments! I'll take a look next day or two and give you feedback/merge.

**Comment by mgechev** [comment]
How about adjusting the boundaries based on the context? I.e. when any of the rectangles that given rectangle depends on, you can pass different boundaries to `ngresizable`.

It seems semantically incorrect have something more than `x`, `y`, `width` and `height` for describing a rectangle in the two dimensional space.

>I ended up with writing the resizable logic myself since the ngOnChanges in the resizable component hindered me from updating (e.g. resetting) the values. I have a use case where I zoom the resizable boxes but that functionality was blocked by the inner recalculations. Is the ngOnChanges really needed or could it be made optional somehow?

This seems like an incorrect behavior of the component. Can you share an example? How does it prevent you from resetting the input values?

Something potentially wrong that I see in [`ngOnChanges`](https://github.com/mgechev/ngresizable/blob/master/lib/ngresizable.component.ts#L93-L98) is that it ignores the boundaries and directly invokes `setSize`. Is your problem related?

**Comment by peboCodemill** [comment]
My scenario is that my rectangles represent time translated to pixels. I have a zoom that modifies the "millisecondsPerPixel" value which resizes the rectangles and should update the values for the bounds. However, when I change the zoom all of the rectangles that haven't been resized yet is resized correctly while a resized "edge" of a rectangle remains the same. I will try to create a JSFiddle of the problem when I have time!

The following is used to modify zoom sizes.
[ngStyle]="itemStyle"
itemStyle = { left: "100px", width: "200px" }

Thanks for all feedback

**Comment by mgechev** [comment]
This seems related to the `ngOnChanges` issue that I pointed out above. Probably, it'll be best if we focus on it. We want to trigger the `RESIZE` action on `ngOnChanges` with the proper settings gotten from the inputs.

I'm afraid I won't be have enough time to work on this until ng-conf is over. If you have some time, a PR will be appreciated!

**Pull request closed without merging**
